language: go

os:
  - linux

go:
  - 1.x
  - master

sudo: false

cache:
  directories:
    - vendor

before_install:
  - sudo apt-get install -y libnotify-bin libnotify-dev

install:
  - make deps

script:
  - make lint
  - make test
