language: go

os:
  - linux

go:
  - 1.x
  - master

sudo: false

cache:
  directories:
    - vendor

addons:
  apt:
    packages:
      - libnotify-bin
      - libnotify-dev

install:
  - make deps

script:
  - make lint
  - make test
