language: go

os:
  - linux
  - osx

go:
  - 1.11.x
  - master

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - libnotify-bin
      - libnotify-dev

script:
  - make lint
  - go build
  - make test
